// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectLanguages():Promise<Array<main.LanguageInfo>>;

export function GetAIConfig():Promise<main.AIConfig>;

export function GetAIProviders():Promise<Array<main.AIProvider>>;

export function GetLanguageConfig():Promise<main.LanguageConfig>;

export function GetMissingPackages(arg1:string):Promise<Array<main.PackageInfo>>;

export function GetPackageTutorials():Promise<Array<main.PackageTutorial>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetThemeConfig():Promise<main.ThemeConfig>;

export function QueryAI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AIResponse>;

export function SaveAIConfig(arg1:main.AIConfig):Promise<void>;

export function SaveLanguageConfig(arg1:main.LanguageConfig):Promise<void>;

export function SaveThemeConfig(arg1:main.ThemeConfig):Promise<void>;

export function SearchPackage(arg1:string,arg2:string):Promise<Array<main.PackageInfo>>;

export function TestFunction():Promise<string>;
