// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectLanguages() {
  return window['go']['main']['App']['DetectLanguages']();
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAIProviders() {
  return window['go']['main']['App']['GetAIProviders']();
}

export function GetLanguageConfig() {
  return window['go']['main']['App']['GetLanguageConfig']();
}

export function GetMissingPackages(arg1) {
  return window['go']['main']['App']['GetMissingPackages'](arg1);
}

export function GetPackageTutorials() {
  return window['go']['main']['App']['GetPackageTutorials']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetThemeConfig() {
  return window['go']['main']['App']['GetThemeConfig']();
}

export function QueryAI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryAI'](arg1, arg2, arg3, arg4);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveLanguageConfig(arg1) {
  return window['go']['main']['App']['SaveLanguageConfig'](arg1);
}

export function SaveThemeConfig(arg1) {
  return window['go']['main']['App']['SaveThemeConfig'](arg1);
}

export function SearchPackage(arg1, arg2) {
  return window['go']['main']['App']['SearchPackage'](arg1, arg2);
}

export function TestFunction() {
  return window['go']['main']['App']['TestFunction']();
}
